[build-system]
requires = []
build-backend = "uv-build"

[tool.uv.workspace]
members = [
    "services/llm",
    "manager/manager",
]

[tool.ruff]
target-version = 'py310'
exclude = ['.venv', 'venv']
