[build-system]
requires = []
build-backend = "uv-build"

[tool.uv.workspace]
members = [
    "services/llm",
    "manager",
]

[tool.ruff]
target-version = 'py310'
exclude = ['.venv', 'venv']

[dependency-groups]
dev = [
    "prefect>=3.4.8",
]
